### ISSUE TITLE
解析后的报告正常生成但是有报错

### ISSUE THREAD

**Issue by dinghuang** [Adrninistrator/java-callgraph2#55]
20:57:01.510 [main] ERROR com.adrninistrator.javacg2.util.JavaCG2FileUtil - 未找到文件 代码解析扩展类名（仅用于显示）
20:57:01.526 [main] ERROR com.adrninistrator.javacg2.util.JavaCG2FileUtil - 处理文件出现异常 代码解析扩展类名（仅用于显示）
com.adrninistrator.javacg2.exceptions.JavaCG2RuntimeException: 未找到文件 代码解析扩展类名（仅用于显示）
        at com.adrninistrator.javacg2.util.JavaCG2FileUtil.getFileInputStream(JavaCG2FileUtil.java:237) ~[run_javacg2.jar:?]
        at com.adrninistrator.javacg2.util.JavaCG2FileUtil.readFile2List(JavaCG2FileUtil.java:300) [run_javacg2.jar:?]
        at com.adrninistrator.javacg2.util.JavaCG2FileUtil.readFile2List(JavaCG2FileUtil.java:289) [run_javacg2.jar:?]
        at com.adrninistrator.javacg2.conf.JavaCG2ConfigureWrapper.getOtherConfigList(JavaCG2ConfigureWrapper.java:224) [run_javacg2.jar:?]
        at com.adrninistrator.javacg2.entry.JavaCG2Entry.recordJavaCG2Config(JavaCG2Entry.java:607) [run_javacg2.jar:?]
        at com.adrninistrator.javacg2.entry.JavaCG2Entry.run(JavaCG2Entry.java:250) [run_javacg2.jar:?]
        at com.adrninistrator.javacg2.entry.JavaCG2Entry.main(JavaCG2Entry.java:94) [run_javacg2.jar:?]
20:57:02.605 [main] ERROR com.adrninistrator.javacg2.entry.JavaCG2Entry - 出现异常
java.lang.NullPointerException: null
        at com.adrninistrator.javacg2.entry.JavaCG2Entry.recordJavaCG2Config(JavaCG2Entry.java:609) ~[run_javacg2.jar:?]
        at com.adrninistrator.javacg2.entry.JavaCG2Entry.run(JavaCG2Entry.java:250) [run_javacg2.jar:?]
        at com.adrninistrator.javacg2.entry.JavaCG2Entry.main(JavaCG2Entry.java:94) [run_javacg2.jar:?]

**Comment by Adrninistrator** [comment]
这是来自zhengyi的邮箱的自动回复邮件。您好，您给我发邮件时我的邮箱未打开，我无法亲自回复您的邮件。我将在进入邮箱后，尽快给您回复。

**Comment by Adrninistrator** [comment]
读取配置文件执行时会有这个问题，通过Java代码传递参数时不会有这个问题，修复代码已提交

**Comment by Adrninistrator** [comment]
读取配置文件执行时会有这个问题，通过Java代码传递参数时不会有这个问题，修复代码已提交
